title: Anki Notes
description: Master learning with Anki and Spaced Repetition
baseurl: ""
url: "https://ankinotes.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

paginate: 10
paginate_path: "/page:num"

collections:
  posts:
    output: true
